### ISSUE TITLE
Major version bump tracking issue

### ISSUE THREAD

**Issue by rondale-sc** [bustle/mobiledoc-kit#666]
This is an issue meant to track the next major version since the build tooling along with a few other changes represent a possible breaking changes to consumers of the addon:

- [ ] https://github.com/bustle/mobiledoc-kit/pull/664 -> Rollup Build
- ~https://github.com/bustle/mobiledoc-kit/pull/665 -> non breaking deprecation but would need to be finalized in major bump since the removal of the deprecation would necessitate a major bump~
- [x] https://github.com/bustle/mobiledoc-kit/pull/658 -> Handle nested section-creating elements in SectionParser (this would allow Ghost to use the main branch of MDK)
- [ ] [Edit 01/17] Seek resolution for this issue: https://github.com/bustle/mobiledoc-kit/issues/667

More to follow

**Comment by kevinansfield** [comment]
I'd really like to see https://github.com/bustle/mobiledoc-kit/pull/658 land if a major version bump is planned. It has some behaviour changes so not strictly a patch although IMO it is mostly fixing buggy behaviour, it's the reason we're currently using a fork including this change at Ghost.

I think it's ready to go but I have a couple of additional verification tests, I'll take a look at those asap.

**Comment by rondale-sc** [comment]
@kevinansfield 	Added to the list! 💯

**Comment by ErisDS** [comment]
I've [commented](https://github.com/bustle/mobiledoc-kit/pull/664#issuecomment-456212961) on #664 which is already listed, that it would be great if mobiledoc-kit could start to be broken down into some smaller pieces. Possibly beyond scope, but if there are any possible quick wins after removing circular dependencies, it would be great to see them considered.

**Comment by mixonic** [comment]
Strong agree on #658.

@ErisDS the work @iezer and @rondale-sc were doing should improve the ability to import the ES modules from mobiledoc-kit directly. I think that is the quickest of quick wins. Bustle has some similar concerns, as they do a lot of import and manipulation of Mobiledoc files.

Specifically @rondale-sc is working up an example of how to use the models and serializer directly and without booting the editor itself. There might be small code tweaks, but mostly we're talking about making the internals a bit better documented and supported.

**Comment by gpoitch** [comment]
Closing as aged maintainer meta. Individual issues are tracked
